---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: all-to-kube-dns
spec:
  description: all endpoints to kube-system:kube-dns
  endpointSelector:
    matchLabels: {}
  egress:
  - toServices:
    - k8sService:
        serviceName: kube-dns
        namespace: kube-system
