---
apiVersion: v1
kind: Secret
metadata:
  name: cilium-ipsec-keys
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
{{- $secretObj := (lookup "v1" "Secret" $.Release.Namespace "cilium-ipsec-keys") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $ipsecGenerate := include "hexRand" 40 }}
{{- $secretValue := (get $secretData "keys" | b64dec) | default $ipsecGenerate | b64enc | quote }}
  keys: {{ $secretValue }}
