---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-conf
  namespace: {{ .Release.namespace }}
data:
  init: |
    #!/bin/bash

    # system
    DEBIAN_FRONTEND="noninteractive"; export DEBIAN_FRONTEND
    echo $SUDO_PASSWORD | sudo -S -k apt-get update
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    python3 \
    python3-pip \
    python-is-python3 \
    software-properties-common

    # docker
    echo $SUDO_PASSWORD | sudo -S -k mkdir -p /etc/apt/keyrings
    echo $SUDO_PASSWORD | sudo -S -k bash -c "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
    echo $SUDO_PASSWORD | sudo -S -k chmod a+r /etc/apt/keyrings/docker.gpg
    echo $SUDO_PASSWORD | sudo -S -k bash -c "echo \
    \"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable\" | tee /etc/apt/sources.list.d/docker.list"
    echo $SUDO_PASSWORD | sudo -S -k apt-get update
    echo $SUDO_PASSWORD | sudo -S -k apt-get install -y docker-ce
    echo $SUDO_PASSWORD | sudo -S -k usermod -aG docker abc

    # extensions
    printf "Installing extensions, please wait."
    extensions="golang.go hashicorp.terraform ms-python.python ms-azuretools.vscode-docker ms-vscode.makefile-tools redhat.vscode-yaml"
    export extensions
    for extension in $extensions; do
        /app/code-server/lib/node /app/code-server --extensions-dir /config/extensions --install-extension "$extension" &
    done
    while true; do
        jobs | grep "Running"
        if [ "$?" -eq 0 ]; then
            printf "."
        else
            echo "done."
            break
        fi
        sleep 3
    done

    printf "Validating extensions..."
    for extension in $extensions; do
        /app/code-server/lib/node /app/code-server --extensions-dir /config/extensions --list-extensions | grep --quiet "$extension"
        if [ "$?" -eq 0 ]; then
            printf "$extension..."
        else
            echo "$extension is not installed!"
            exit 1
        fi
    done
    echo "done."

    # dark theme
    if test -f "/config/data/User/settings.json"; then
        echo "Good to go"
    else
        tee /config/data/User/settings.json << EOM
    '{                                                                                  
        "workbench.colorTheme": "Visual Studio Dark"
    }'
    EOM
        echo "Good to go"
    fi
