---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Release.namespace }}
data:
  nginx.conf: |
    events {
    }
    http {
        server {
            server_name code;
            listen [::]:9443 ssl ipv6only=on;
            listen 9443 ssl;
            ssl_certificate /etc/nginx/certs/tls.crt;
            ssl_certificate_key /etc/nginx/certs/tls.key;

            location / {
                proxy_buffering off;
                proxy_pass http://localhost:8443/;
            }
        }
    }
