---
apiVersion: v1
kind: Pod
metadata:
  name: code
  namespace: {{ .Release.namespace }}
  labels:
    app: code
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
    - containerPort: 9443
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx
    - name: nginx-secret
      mountPath: /etc/nginx/certs
  - name: code
    image: linuxserver/code-server:4.9.1
    env:
    - name: SUDO_PASSWORD
      valueFrom:
        secretKeyRef:
          name: code
          key: password
          optional: false
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: code
          key: password
          optional: false
    - name: DOCKER_HOST
      value: tcp://localhost:2376
    volumeMounts:
    - name: docker-certs
      mountPath: /certs
    - name: code-conf
      mountPath: /custom-cont-init.d
    - name: code-storage
      mountPath: /config
    - name: docker-storage
      mountPath: /var/lib/docker
  - name: dind-daemon
    image: docker:dind
    resources:
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-storage
      mountPath: /var/lib/docker
    - name: docker-certs
      mountPath: /certs
  restartPolicy: Never
  volumes:
  - name: code-conf
    configMap:
      name: code-conf
  - name: code-storage
    persistentVolumeClaim:
      claimName: code-storage
  - name: docker-storage
    persistentVolumeClaim:
      claimName: docker-storage
  - name: docker-certs
    emptyDir:
      sizeLimit: 1Gi
  - name: nginx-conf
    configMap:
      name: nginx-conf
  - name: nginx-secret
    secret:
      secretName: tls
      optional: false
