---
apiVersion: v1
kind: Secret
metadata:
  name: code
  namespace: {{ .Release.namespace }}
type: Opaque
data:
{{- $secretObj := (lookup "v1" "Secret" $.Release.Namespace "code") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $secretValue := (get $secretData "password" | b64dec) | default (randAlphaNum 36) | b64enc | quote }}
  password: {{ $secretValue }}
---
{{- $tls := genSelfSignedCert "code" nil nil 365 }}
apiVersion: v1
kind: Secret
metadata:
  name: tls
  namespace: {{ .Release.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $tls.Cert | b64enc | quote }}
  tls.key: {{ $tls.Key | b64enc | quote }}
