---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: code
  name: code
  namespace: {{ .Release.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "app=code"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "3"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "6"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
  - name: http
    port: 443
    targetPort: 9443
  selector:
    app: code
  type: LoadBalancer
  externalTrafficPolicy: Local
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "from-world-to-code"
  namespace: {{ .Release.namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: code
  ingress:
  - fromEntities:
    - all
  egress:
  - toEntities:
    - all
